language: python
python:
- '2.7'
install: pip install -r requirements.txt
script:
- python tests.py
env:
  global:
  - NOTIFY_TEST_REMOTE_BROWSER=YES
  - APP_SETTINGS="config.TestingConfig"
before_script:
- curl -L https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash
- python app.py &
notifications:
  webhooks: http://project-monitor.codeforamerica.org/projects/197a4506-1dea-4340-a3a1-013dd0dc2db9/status
